version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: app-mysql
    volumes:
       - ./app.mysql:/docker-entrypoint-initdb.d/app.mysql
       - ./data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: intelipost
        MYSQL_DATABASE: app
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'intelipost'
    ports:
      - "3306:3306"
  app:
      depends_on:
        - mysql
      build: .
      links:
        - mysql
      container_name: app
      ports:
        - "5000:5000"
      restart: always
      volumes:
        - ./:/app
      environment:
        MYSQL_HOST: mysql:3306
        MYSQL_USER: user
        MYSQL_PASSWORD: intelipost
        MYSQL_DB: app